name: Npm

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # tag=v6.3.0
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Publish package
        run: |
          npm install -g npm@latest
          npm ci
          npm publish
